server: hub-cloud.browserstack.com
user: BROWSERSTACK_USERNAME
key: BROWSERSTACK_ACCESSKEY

common_caps:
  build: capybara-browserstack
  browserstack.debug: true

browser_caps:
- browser: chrome
- browser: firefox
- browser: internet explorer
- browser: safari
